name: Android Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PREVIEW_API_LEVEL: 36
      PREVIEW_BUILD_TOOLS: 36.0.0-rc1

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Restore Android SDK cache
        id: restore-android-sdk
        uses: actions/cache/restore@v4
        with:
          path: |
            ${{ env.ANDROID_SDK_ROOT }}/platforms/android-${{ env.PREVIEW_API_LEVEL }}
            ${{ env.ANDROID_SDK_ROOT }}/build-tools/${{ env.PREVIEW_BUILD_TOOLS }}
            ${{ env.ANDROID_SDK_ROOT }}/licenses
          key: android-sdk-preview-${{ runner.os }}-${{ env.PREVIEW_API_LEVEL }}-${{ env.PREVIEW_BUILD_TOOLS }}

      - name: Set up Android SDK
        if: steps.restore-android-sdk.outputs.cache-hit != 'true'
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: latest
          packages: |-
            platform-tools

      - name: Install preview SDK components
        if: steps.restore-android-sdk.outputs.cache-hit != 'true'
        run: |
          yes | sdkmanager --licenses
          yes | sdkmanager --channel=3 "platforms;android-${{ env.PREVIEW_API_LEVEL }}" "build-tools;${{ env.PREVIEW_BUILD_TOOLS }}"

      - name: Save Android SDK cache
        if: steps.restore-android-sdk.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: |
            ${{ env.ANDROID_SDK_ROOT }}/platforms/android-${{ env.PREVIEW_API_LEVEL }}
            ${{ env.ANDROID_SDK_ROOT }}/build-tools/${{ env.PREVIEW_BUILD_TOOLS }}
            ${{ env.ANDROID_SDK_ROOT }}/licenses
          key: android-sdk-preview-${{ runner.os }}-${{ env.PREVIEW_API_LEVEL }}-${{ env.PREVIEW_BUILD_TOOLS }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: ${{ github.event_name == 'pull_request' }}

      - name: Build debug APK
        run: ./gradlew assembleDebug

      - name: Build release APK
        if: github.ref == 'refs/heads/main'
        run: ./gradlew assembleRelease

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk

      - name: Upload release APK
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: app/build/outputs/apk/release/*.apk
