name: Android Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '**/*.md'

env:
  JAVA_VERSION: '21'
  ANDROID_PLATFORM_API: '36'
  ANDROID_BUILD_TOOLS: '36.0.0-rc1'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: gradle

      - name: Install Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: latest
          packages: |-
            platform-tools

      - name: Install Android SDK components
        run: |
          yes | sdkmanager --licenses
          yes | sdkmanager --channel=3 "platforms;android-${ANDROID_PLATFORM_API}" "build-tools;${ANDROID_BUILD_TOOLS}"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: github.ref != 'refs/heads/main'

      - name: Build debug APK
        # if non-main branch: not writing to Gradle cache.
        # if main branch: writing to Gradle cache.
        run: |
          ./gradlew assembleDebug

      - name: Build release APK
        if: github.ref == 'refs/heads/main'
        # main branch, last build step: stop writing to Gradle cache.
        run: |
          echo "org.gradle.configuration-cache.read-only=true" >> gradle.properties
          ./gradlew assembleRelease

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk

      - name: Upload release APK
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: app/build/outputs/apk/release/*.apk
